version: "3"
services:
  www:
    build:
      context: www
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_OKTA_OAUTH2_ISSUER=${OKTA_OAUTH2_ISSUER}
      - REACT_APP_OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - REACT_APP_API_ENDPOINT=${API_ENDPOINT}
      - REACT_APP_GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT}
  api:
    build:
      context: api
    ports:
      - "8080:8080"
    environment:
      - OKTA_OAUTH2_ISSUER=${OKTA_OAUTH2_ISSUER}
      - OKTA_OAUTH2_CLIENT_ID=${OKTA_CLIENT_ID}
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
      - "9080:8080"
    depends_on:
      - "db"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey