version: "3"
services:
  www:
    build:
      context: www
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_OKTA_OAUTH2_ISSUER=${OKTA_OAUTH2_ISSUER}
      - REACT_APP_OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - REACT_APP_API_ENDPOINT=${API_ENDPOINT}
  api:
    build:
      context: api
    ports:
      - "8080:8080"
    environment:
      - OKTA_OAUTH2_ISSUER=${OKTA_OAUTH2_ISSUER}
      - OKTA_OAUTH2_CLIENT_ID=${OKTA_CLIENT_ID}
