# https://cloud.google.com/cloud-build/docs/configuring-builds/store-images-artifacts
steps:
  - name: gcr.io/cloud-builders/npm
    args: ["install"]
    dir: "www"
  - name: "gcr.io/cloud-builders/npm"
    args: ["run-script", "build"]
    env:
      - "REACT_APP_API_ENDPOINT=${_REACT_APP_API_ENDPOINT}"
      - "REACT_APP_OKTA_OAUTH2_ISSUER=${_REACT_APP_OKTA_OAUTH2_ISSUER}"
      - "REACT_APP_OKTA_CLIENT_ID=${_REACT_APP_OKTA_CLIENT_ID}"
      - "REACT_APP_BASE_NAME=${_REACT_APP_BASE_NAME}"
      - "REACT_APP_PUBLIC_URL=${_REACT_APP_PUBLIC_URL}"
    dir: "www"
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "-r", "www/build/*", "${_BUILD_PUBLISH_DESTINATION}"]
